webdriverio/selenium-standalone

conf.js
conf.js assumed hub url port of 4444
if -port 222 is passed as selenium server argument
the server will start but then get killed after 60s timeout
added simple argument parser specifically looking for
a port passed as selenium standalone argument
=> update config settings

README.md
selenium-standalone was a missing ingredient in my workflow, so I wrote a post about integrating it with WebdriverIO + Gulp + Mocha.
At first I was struggling a bit because the recommended usage seemed to be installing and running it globally, and I wanted to run it programmatically to minimize any global deps. Finally, I came up this and it seems to work very well.
If you don't think it's useful, feel free to close :wink:
=> Add integration example Gulp + WebdriverIO + Mocha

lib/compute-download-urls.js, lib/compute-fs-paths.js, lib/install.js, lib/start.js
This makes Chrome and IE drivers optional. The default behavior remains (for backwards compatibility) to include them in both `install` and `start`, but they can be disabled as follows:
```js
{
drivers: {
chrome: false,
ie: false
}
}
```
=> Optional Chrome and IE drivers. Fixes #123.

lib/get-selenium-status-url.js
This fixes the following:
```
starfall@nx:~/workspace/backuphamster-deployment$ selenium-standalone start
module.js:338
throw err;
^
Error: Cannot find module 'URIjs'
at Function.Module._resolveFilename (module.js:336:15)
at Function.Module._load (module.js:278:25)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at Object.<anonymous> (/home/starfall/.npm-packages/lib/node_modules/selenium-standalone/lib/get-selenium-status-url.js:3:11)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Module.require (module.js:365:17)
```
Could you please release a new version?
=> Fix critical bug

README.md, bin/selenium-standalone
It'll allow transparent installation using npm scripts, like in the following
`package.json` example:
```json
{
"scripts":{
"install":"echo 'Installing selenium...'; selenium-standalone install --silent"
}
}
```
=> Add install `--silent` option

lib/check-started.js, lib/get-selenium-status-url.js, test/get-selenium-hub-test.js
When `selenium-standalone` is run with only the `-role node` mode, eventually the process will die because the server status URL is returning an error. Example:
Looking at the only API documentation that I could find [0] and my own selenium test servers it appears that the `/wd/hub/status` API will always fail when called against the hub, but passes when called against a node. This PR changes to check against the `/grid/api/hub` API if running in a grid hub role (API to use was gotten from [0] and the selenium unit tests[1]). When running in a standalone mode or grid node, continue to use the existing API for checking status.
There was also some existing logic that tried to use the `-hub` parameter to decide what host the status check should query. It seems that the `checkStarted()` wants …
=> Process can incorrectly terminate when running as a grid node

lib/default-config.js
Selenium version `2.50.1` and IE version `2.50.0` via http://www.seleniumhq.org/download/
Chromedriver version `2.21` via https://chromedriver.storage.googleapis.com
=> feat(upgrades): upgrade default versions

lib/install.js, lib/start.js, test/programmatic.js
Fixes #128.
Let me know if this makes any sense. I tried to add a meaningful test, but `ChildProcess.spawnargs` is the only way I know to peek into the internals. It’s only available in newer Node versions. I’ve tested successfully with 0.10, 0.12 and 5.5, but only 5.5 can perform the `spawnargs` check.
This is an API-breaking change in terms of semver AFAICS. Existing code might depend on the fact that the default options are always merged in. Was there a specific reason to do this in the first hand?
=> Do not merge the install/start options with the default options.

lib/install.js, package.json
Replaces unmaintained unzip dependency with yauzl.
This removes the indirect dependency to the deprecated graceful-fs@3.x.
=> Remove deprecated graceful-fs@3.x dependency

bin/selenium-standalone, lib/compute-download-urls.js, lib/compute-fs-paths.js, lib/default-config.js, lib/install.js, lib/start.js
Required for Firefox 47+, supported for Firefox 45+
`geckodriver` executable is distributed as a .gz file for linux and osx,
so I've added a new gunzip workflow similar to the unzip workflow
Fixes #181
=> Add support for Firefox Marionette Driver

README.md
- Command Line has an interface, not an API
- Programmatic API is redundant
=> Tweak headers in README

README.md
The file which is actually holding the up-to-date default config is not mentioned anywhere in the Readme. (It is `lib/default-config.js`)
=> Mention default config in the Readme

lib/compute-download-urls.js
* On versions of Chromedriver < 2.23 the filename ends with `mac32`.
* With this fix, attempting to install chromedriver 2.22 and earlier via `selenium-standalone install` will succeed. This was called out in https://github.com/vvo/selenium-standalone/issues/209
To Test:
```
selenium-standalone install --drivers.chrome.version=2.22 --drives.chrome.baseURL=https://chromedriver.storage.googleapis.com
```  
@vvo @nkbt
=> Fix building previous chromedriver version urls

.travis.yml
Did some research into fixing the travis-ci builds since the unit tests have been failing for some time, but always pass locally. Selenium has a problem where if it was started and stopped in quick succession, the startup time would get longer and longer [0]. This is basically what is going on with our unit tests. Specifically, the problem with with how Selenium is getting a random session [1]. The Travis build environment appears to have very low entropy [2] which heightens the chance of hitting this problem.
There were a handful of workarounds listed in the below references that never really seemed to pan out and get consistently passing tests. What did work? Using the new travis-ci container-based infrastructure [3] gives us not only consistently passing tests, but also much quicker …
=> Stabilize unit tests in travis-ci 

lib/compute-download-urls.js, test/compute-download-urls-test.js
There has been a number of PRs lately that improved how the URLs for binaries are generated. These helped us support older/newer versions of drivers where the structure of the filenames have been changed.
Since there is likely more of these types of changes necessary in the future, it is a good time to have some test cases in place to ensure that any future improvements support existing workflows as much as possible. This PR adds a non-exhaustive number of tests based on the conditionals that I found in the code.
NOTE: These tests do not verify that the module is returning valid URLs that will respond with the desired binary files. It is just testing that the URL is constructed how we expected.
=> Test cases for constructing download URLs

lib/start.js
Selenium 3 changed how their command line arguments were parsed. Now they use the java standard of having properties set before the jar. See https://github.com/SeleniumHQ/selenium/issues/2566
```shell
java -Dwebdriver.chrome.driver=... -Dwebdriver.gecko.driver=...  -jar server.jar
```
---
Fixes https://github.com/vvo/selenium-standalone/issues/218
=> Fix launching selenium 3.0-beta server

lib/start.js, test/programmatic.js
```text
$ ./bin/selenium-standalone start -version=2.53.1 -- -port 5556
13:29:49.643 INFO - Launching a standalone Selenium Server
13:29:49.673 INFO - Java: Oracle Corporation 25.45-b02
13:29:49.673 INFO - OS: Mac OS X 10.10.5 x86_64
...
```
```text
$ ./bin/selenium-standalone start -version=3.0.0-beta2 -- -port 5556
13:27:34.467 INFO - Launching a standalone Selenium Server
13:27:34.499 INFO - Java: Oracle Corporation 25.45-b02
13:27:34.499 INFO - OS: Mac OS X 10.10.5 x86_64
...
```
---
Fixes #225
=> Fix launching with custom arguments

README.md, bin/selenium-standalone, package.json, test/cli-parameters.js, test/fixtures/config.invalid.js, test/fixtures/config.invalid.json, test/fixtures/config.valid.js, test/fixtures/config.valid.json
Support for the `--config=<path>` option for specifying a config file instead of command line arguments (#230) 
Included unit tests (#238) requested by @stephenash
=> Support for --config option

lib/install.js, package.json
Hi,
Just a quick bump of a few dependencies that were causing npm warnings on recent node versions.
Had to add a little code for request since its [version 2.59.0](https://github.com/request/request/blob/master/CHANGELOG.md#v2590-20150720) fixed HEAD behavior, which is actually rejected by S3, so a GET request is needed.
I have very little experience with this module so maybe my indexOf strategy is not the best, but it works for the default case.
=> Bump request and mocha to avoid npm warnings

.travis.yml, lib/install.js
Previous PR added `Object.assign`, which is not available in node <4
I added node.js versions travis config to be sure to cover this in next PRs
=> Object.assign n/a in node 0.x

lib/default-config.js, lib/install.js, test/default-downloads-test.js
Provides fix for #261.
Also adds some new test cases that try to download all the binaries that come with the defaults. Hopefully the new tests will help us catch any problems when the default versions change or the paths to the remote files change.
* Selenium Server
* IE (win32, win64)
* Chrome (linux32, linux64, mac, win32)
* Firefox (linux32, linux64, mac, win32, win64, arm)
=> Update default value for IE driver to one that exists.

lib/default-config.js
Bumping to 2.28, fixes automation extension bug in Chrome. 
See:
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1625&can=1&q=screenshot&colspec=ID%20Status%20Pri%20Owner%20Summary
=> ChromeDriver bump.

lib/default-config.js, test/default-downloads-test.js
Update version to the latest version
Reason
Latest gecko is dependent on latest selenium driver. The 32-bit linux version of Geckodriver 0.15.0 is missing. See: https://github.com/mozilla/geckodriver/releases.
=> update Selenium and Geckodriver versions

HISTORY.md, README.md, lib/default-config.js, package.json
Chromium [released chromedriver 2.30](https://sites.google.com/a/chromium.org/chromedriver/downloads)  today
Defaulting **chromedriver** to **2.30** will fix issues when trying to resize the browser when using **Chrome headless**.
The following APIs have been moved from being an extension to being part of the Dev Tools
https://chromedevtools.github.io/devtools-protocol/tot/Browser/#method-setWindowBounds
As chrome headless does not allow the use of extensions then resizing the browser fails with any version lower than 2.30.
Binaries available here:
https://chromedriver.storage.googleapis.com/index.html?path=2.30/
=> Update chromedriver to default to 2.30

HISTORY.md, README.md, lib/default-config.js, package.json
Chromium [released chromedriver 2.31](https://sites.google.com/a/chromium.org/chromedriver/downloads) yesterday
Defaulting **chromedriver** to **2.31** will fix issues when trying to use the sendKeys API (input keystrokes to the browser) when using **Chrome headless**.
Details of the fix can be found in this bug tracker
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1772
With merge request here
https://codereview.chromium.org/2952383002
Binaries available here:
https://chromedriver.storage.googleapis.com/index.html?path=2.31/
=> Update default chromedriver to 2.31

lib/get-selenium-status-url.js, test/fixtures/config.node.json, test/get-selenium-hub-test.js
As mentioned in selenium server documentation it is possible to pass the node configuration options via -nodeConfig parameter (https://github.com/SeleniumHQ/selenium/wiki/Grid2#configuring-the-nodes-by-json). 
Unfortunately selenium-standalone didn't had support for that parameter and was constructing the status check URL incorrectly. Therefore node was stopping after several failed attempts.
I changed selenium status page URL construction to take into account host, port parameters defined in node config file and added tests.
=> Fix selenium server status check URL when passing node config file

README.md, lib/install.js
Our build fails given at times it's unable to download microsoft edge driver given the url seems to be flaky at times. There are solutions out there that suggest to change our network configuration, but given we only use chrome, it sounds about right not to install all drivers if the only one we want is chrome...
=> adding the ability to install single driver

lib/compute-download-urls.js, lib/default-config.js, test/compute-download-urls-test.js, test/default-downloads-test.js
Updates chromedriver to 2.36.
Chromedriver doesn't support linux 32 after 2.33 so this updates the tests and throws an error for linux 32 > chromedirver 2.33.
=> Update chromedriver to 2.36 and updates for linux 32

.travis.yml, package.json
It seems to be failing because of node 0.12 
This PR fixes a security vulnerability found in the hoek module before version 4.2.1
node 0.12 is no more maintained since 2016-12-31  : https://github.com/nodejs/Release#release-schedule
I suggest to drop support for it.
=> Update requests dependency

lib/default-config.js
Geckodriver 0.20.0 + Firefox 66.0.1 fails when attempting to click on an element which is visible in page but has `elem.getBoundingClientRect().height === 0`. I tested this with `wdio` on `document.body`
Geckodriver 0.20.1 + Firefox 66.0.1 works
Example of page in Firefox that reports height 0 on `document.body`:
Q: @vvo have you ever considered having some e2e tests of browser quirks in different Browser + Webdriver combinations?
=> Updated to the latest Geckodriver that works with Firefox 66.0.1

lib/default-config.js, lib/microsoft-edge-releases.js
Compatibility with JRE10 has been added to selenium recently. The workaround that is linked to in #369 hints in this direction.
This would resolve https://github.com/vvo/selenium-standalone/issues/369
I also bumped the versions numbers of chromedriver, iedriver, and edge drivers.
Removed links to webdriver for Edge 12 and 13 because they are no longer offered by Microsoft to make the CI pass.
=> Bumped selenium version to 3.12.0 so that it runs in Java 10

README.md, lib/default-config.js
Chromium [released chromedriver 2.39](https://sites.google.com/a/chromium.org/chromedriver/downloads)
This increases support for stable and beta builds of Chrome (v67 & v68)
Binaries available here:
https://chromedriver.storage.googleapis.com/index.html?path=2.31/
=> Update default chromedriver to 2.39

docker/Dockerfile, docker/scripts/start.sh, docker/scripts/utils.sh
2 use cases:
* When building/releasing new version of the Docker image, admin will be able to easily update HISTORY with both browsers and Selenium versions
* When using the Docker image, users will easily be able to debug potential issues
=> Display Selenium environment information when building and starting the Docker image

lib/default-config.js
When using the latest version of Firefox, I'm seeing some issues with the default version of gecko driver, updating to the latest release `0.23.0` appears to fix this for me - I'm not sure if there is a wider implication to making this change, I'd love a steer and apologise for adding noise if this is out of scope/not helpful
=> [WIP] Update default config to use latest gecko driver

lib/default-config.js
The recent update to `3.141.0` I've found that Selenium throws an exception when run on a single cpu.
```
Exception in thread "main" java.lang.IllegalStateException: Insufficient configured threads: required=3 < max=3 for QueuedThreadPool[qtp707610042]@2a2d45ba{STARTED,3<=3<=3,i=3,q=0}[ReservedThreadExecutor@2f7c2f4f{s=0/1,p=0}]
```
`3.141.5` has now been released, with this fix in.
=> updated the selenium server jar version

docker/Dockerfile, docker/scripts/start.sh
Currently, `docker stop` command does *not* gracefully shutdown the container. It tries to terminate the main process in the container, timeouts (10s.) and finally kill the main process.
=> Add Tini tooling to ensure graceful shutdown of the Docker container

.travis.yml, README.md, bin/selenium-standalone, test/cli-parameters.js, test/fixtures/config.ignoreExtraDrivers.js
**Issues:** #433, #361, #325 
**Solution:** Add `opts.ignoreExtraDrivers` flag to prevent installing and attempting to start unwanted drivers from default config. When set to `true`, unwanted default config drivers are ignored (e.g., only Chrome is desired and used) when using CLI install/start commands. API install/start commands already function this way. This solution is backward-compatible. Added one new unit test to communicate/validate this new behavior; all existing tests passing. Also verified CLI `start` command with a custom config containing only one driver (Chrome) and option `ignoreExtraDrivers=true` executes successfully without error when other drivers (IE, Firefox, Edge) are not installed. Also added documentation of new config option to README.
**Edit:** Fixed failing …
=> Ignore extra drivers from default config file using CLI and custom config file

lib/install.js
When using 
```sh
selenium-standalone install --version=3.6.0 --baseURL=http://my.mirror.com/selenium-server --drivers.chrome.version=2.33 --singleDriverInstall=chrome --drivers.chrome.baseURL=http://my.mirror.com/chromedriver`
```
Selenium ignore the `--drivers.chrome.baseURL` part and says :
```sh
----------
selenium-standalone installation starting
----------
---
selenium install:
from: http://my.mirror.com/selenium-server/3.6/selenium-server-standalone-3.6.0.jar
to: D:\x\y\z\node_modules\selenium-standalone\.selenium\selenium-server\3.6.0-server.jar
---
chrome install:
from: https://chromedriver.storage.googleapis.com/2.33/chromedriver_win32.zip
to: D:\x\y\z\node_modules\selenium-standalone\.selenium\chromedriver\2.33-x64-chromedriver
```
=> fix(install): prefer the user config rather that the default one

README.md, lib/compute-download-urls.js, lib/compute-fs-paths.js, lib/default-config.js, lib/install.js, lib/start.js, test/compute-download-urls-test.js, test/no-reinstall.js
Add a new browser to the list of supported ones: Chromium Edge.
This change does not affect legacy edge, as there could be some users who might still want to use it.
The webdriver unzipping process was also slightly updated to support zips which might contain folders and not just the webdriver binary (which is the case for the latest chromium edge drivers)
=> add support for chromium edge

lib/default-config.js
Updated Chromedriver Version.
Tested via `npm run start` and checked .selenium/chromedriver folder
=> Updated Chromedriver Version

HISTORY.md, README.md, lib/check-paths-existence.js, lib/compute-download-urls.js, lib/default-config.js, lib/install-utils.js, lib/install.js, package.json, test/compute-download-urls-test.js, test/default-downloads-test.js, test/no-files.js, yarn.lock
support `latest` as Chrome, Firefox, and ChromiumEdge version and set it as default one.
Additionally, had to remove `async` package.
#468 #502 #511
=> Support latest as browser driver version

lib/check-started.js, lib/install-utils.js, lib/install.js, lib/log-error.js
- add more logging
- increase timeouts
=> add more logging, increase timeout

docs/API.md, docs/CLI.md, lib/compute-download-urls.js, lib/install.js, test/compute-download-urls-test.js
Allow specifying full URLs for selenium and browser drivers.
With the PR it should be possible to download selenium v4 alpha
resolves: #437 #445
=> full url support

lib/compute-download-urls.js
There is a typo in following error message
```
Only x64 architecture is available for chroimum edge driver for linux
```
=> Fix "chromium" typo

lib/install-utils.js
I was using selenium with jest and I got complaints about an open handle in install-utils. My hypothesis is that the test setup that I am using does not use `uncompressGzippedFile` function and the gunzip stream is never used/closed. Moving the creation of the gunzip stream inside the method fixed my problem.
=> Fix open handle in install-utils

lib/install.js, lib/log-error.js
As edge driver is unavailable for a few versions on fewer platforms, Webdriverio fails to start the server with 404 messages.
This PR is to print a precise message in case if this happens.
**Note**: This issue only occurs for chromiumedge webdriver downloads.
HI @christian-bromann,
May not be perfect, but let me know if this works!
=> Add message for edgedriver download failures

lib/compute-download-urls.js, test/compute-download-urls-test.js
Added patch version zeroing for selenium-server v4 downloading.
Added a few tests for v4 url generations.
Fixes #604
=> Fix selenium-webdriver patch versions dowload for v4

lib/start.js
Could not get the test suite to pass. Ran into two issues due to options (or lack of options) being passed to the `start` function. Rather than adjust the test suite to pass the necessary option I thought it would be better to adjust the API to have defaults so the options are not necessary.
Spawn Options Stdio
================
This defaults to [`pipe`](https://nodejs.org/api/child_process.html#optionsstdio). With this default the behavior I was getting is that the `checkStarted` was always failing. This was obviously not an issue at some point. I am guessing that the selenium jar file changed it's behavior so that it didn't fully boot up until some stdio activity occurred and since this library is not interacting with that pipe it remained not booted.
I noticed the …
=> Adjustments to `start` Options

lib/compute-download-urls.js, test/compute-download-urls-test.js
This should fix #659.
I divided this up into two commits. The first is just the simple fix along with an update to the unit tests to match.
But obviously the tests were passing just fine previously even though the URLs were invalid. Therefore the second commit ups our testing so we are doing a smoke test against the URL for every released version (according to Github). This should prevent a similar regression in the future.
Since this test uses the internet I did make it bail out and skip the test if it can't get that release list under the idea that the developer is disconnected. I had to increase the timeout a bit for that test. On my machine it took a bit over 2 seconds to get that release list and check each URL. 5 seconds should give padding if someone has a slow connection.
If this …
=> Fix Selenium URLs prior to v4

lib/check-started.js
After more details testing found that timeout for got utils and timeout for startup checks should be different. 
Also in gotOptions timeout should be `object` according to [documentation](https://github.com/sindresorhus/got/blob/6f5c7ce1233c7a28fed12d64766fa19e8eb3b345/documentation/6-timeout.md)
=> bug #617 improve timeouts for GOT utils

lib/install-utils.js, lib/install.js, test/no-reinstall.js
This should resolve #658.
I realized it was also downloading the Selenium jar file since that is now also hosted on Github and therefore the assumed etag generation of MD5 was not the proper request. This also allowed me to remove the special MSEdge as the fault was not with their system but the requests this software was making (they are also not using MD5).
Since there are a number of changes I have broken it down the following pieces to make it easier to digest:
* 3182e23 - The first order of business is to have a failing test. Fortunately there was already a test just for this issue. Unfortunately it was passing when it should not be. ☹️  I looked at the git history and it appears it was originally correct but in 2da8f60 it was updated to be incorrect (and basically always pass). The …
=> Fix Conditional HTTP Requests

lib/start.js, test/programmatic.js
This is a follow-up to #660.
The "should start with the given drivers" test was not passing for me. I believe this is because `--detect-drivers` is auto-loading drivers it can find on some peoples system but on my system there are no drivers in the PATH so it causes an error by the JAR file. Either that or it is failing for everybody and the JAR file changed behavior recently to throw an error when no drivers can be found and `--detect-drivers` is enabled.
In #660, I thought `--detect-drivers` only did auto-detection and since we were specifying the path to all drivers it should not be needed. By setting that to false it caused the tests to pass. Unfortunately as @wyhmichael correctly pointed out that option will stop all loading of drivers not just the ones auto-detected. We should be …
=> Fix conditional driver loading

lib/start.js
#670 changed the launching of `selenium-server.jar` to only allow certain browsers. Although there is no driver that needs downloading for Safari (apparently SafariDriver is available on all Macs), we should still allow Safari to be launched.
Testing:
- Verified that I can now request `browserName: 'safari'` and that Safari loads on my Mac
=> feat: Allow Safari to be launched

lib/compute-download-urls.js, test/compute-download-urls-test.js
I had an issue yesterday downloading the latest Chromium EdgeDriver on my M1 MacBook Air from a fresh install. It turns out that the latest EdgeDriver version had only been released for Linux. Seemingly Microsoft releases each different OS versions one at a time, not updating everything all at once. Even this morning, I see that selenium-standalone cannot download the latest version, it uses the fallback version 96.0.1054.34 even though I can manually download the latest versions from https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/
I do not have a solution for that (maybe I should enter a bug about the fallback mechanism being suboptimal?), but while investigating, I realized that selenium-standalone is not downloading the arm64 version of EdgeDriver for arm64 Macs …
=> Use Mac arm64 EdgeDriver when available

lib/install-utils.js
Use case:
When downloading [Chrome Canary builds](https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json), the chromedriver file is nested within other folders.
This allows selenium-standalone to properly download and then extract these builds.
Without this, the chromedriver binary fails to extract, automation cannot proceed.
To test:
```ts
const drivers = {
firefox: true,
chrome: {
version: '117.0.5858.0',
arch: 'arm64'
fullURL: `https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5858.0/mac-arm64/chromedriver-mac-arm64.zip`,
},
chromiumedge: {
version: 'latest',
arch: process.arch,
baseURL: 'https://msedgedriver.azureedge.net/',
}
// in wdio.conf.ts
services: [
['selenium-standalone', {
installArgs: {
version: "4.10.0",
baseURL: …
```
=> Allows nested files to be unzipped, properly test for folders

lib/platformDetection.js
I got this issue during downloading of the drivers, it seems to be a result of the detectBrowserPlatformInternal, it returns 
```'mac-arm64' : 'mac-x64'```, but those options are not available in getArhType switch/case 
```sh
selenium install:
from: https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.9.0/selenium-server-4.9.0.jar
to: /node_modules/selenium-standalone/.selenium/selenium-server/4.9.0/selenium-server.jar
---
chrome install:
from: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.96//chromedriver-undefined.zip
to: /node_modules/selenium-standalone/.selenium/chromedriver/latest-mac-x64/chromedriver
---
File from https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.9.0/selenium-server-4.9.0.jar has already been downloaded …
```
=> fix/getArhType due to result of the detectBrowserPlatformInternal

.github/dependabot.yml, HISTORY.md, README.md, docs/API.md, docs/CLI.md, lib/default-config.js, lib/processKiller.js, lib/start.js, package-lock.json, package.json, test/process-killer-test.js
@christian-bromann Generally it's a good feature when we can check and kill selenium processes by port :4444 and drivers names before starting.
Tests added
Bug is here https://github.com/webdriverio/selenium-standalone/issues/599
And I'm not convinced but maybe it have sense to be switched on in config by default. Currently it's not switched on.
=> Process killer feature

README.md, bin/selenium-standalone, docs/API.md, docs/CLI.md, lib/compute-fs-paths.js, lib/default-config.js, lib/driver-starter.js, lib/install-utils.js, lib/install.js, lib/processKiller.js, lib/start.js, test/only-driver-tests.js, test/process-killer-test.js
Hi @christian-bromann  here is new feature onlyDriver it allow to install or start any driver directly without selenium-server (prevented from downloading also)
Ports for drivers by default:
for chromedirver port is 9515
for edgedriver port  is 9515
for firefox port  is 4444
The ports can be changed in onlyDriverArgs
Before each driver execution process killer check port and process name existence
related to https://github.com/webdriverio/selenium-standalone/issues/843
=> onlyDriver feature

lib/default-config.js, lib/install-utils.js, lib/install.js, package-lock.json, package.json
Previous assumption with saving etag file haven't been worked. etag file has been saving before downloading any files that's why we didn't know, regarding files, have been downloaded it properly or not. If damaged file exist it can be deleted only manually for resolving the issue. The behaviour is leeding to blocking using the package.
Current approach 
1. It's compared content length from server and fs.stat().size from local file
2. if 1 step isn't valid it compares etag/md5 from server with md5 from local file.
3. if 1,2 step aren't valid it's downloading new files and rewrite it
related with https://github.com/webdriverio/selenium-standalone/issues/788
=> checking downloaded file size with server size

lib/compute-download-urls.js
This fixes a small error when installing the chromium edge driver on the arm64 architecture. When the user selects "latest" for version, we were not passing the version info to the getChromiumEdgeDriverArchitectureOld function from chromiumEdgeBundleAvailable. This caused the function to fail silently, which would revert to the fallback version even if a later version was available.
=> [fix] chromiumedge driver doesn't install on arm64 when user specifies "latest" for version

lib/compute-download-urls.js, lib/default-config.js
Current url does not work for latest drivers: https://github.com/GoogleChromeLabs/chrome-for-testing/pull/108
```
404 https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.184/mac-arm64/chromedriver-mac-arm64.zip
Response code 404 (Not Found)
```
Works well with the updated urls
=> fix: Update chromedriver download base url

.github/workflows/release.yml
- Replace the deprecated `::set-output` ﻿workflow commands.
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/.
=> refactor: Remove deprecated ::set-output command

.github/workflows/update.yaml
* Bump lewagon/wait-on-check-action to 1.3.3 to unblock the Dependabot PRs.
Here is an example from [webdriverio/selenium-standalone](https://github.com/webdriverio/selenium-standalone/actions/runs/7958535376/job/21723602654?pr=876):
```
Installing Bundler
/opt/hostedtoolcache/Ruby/2.7.4/x64/bin/gem install bundler -v ~> 2
ERROR:  Error installing bundler:
The last version of bundler (~> 2) to support your Ruby & RubyGems was 2.4.22. Try installing it with `gem install bundler -v 2.4.22`
bundler requires Ruby version >= 3.0.0. The current ruby version is 2.7.4.191.
```
* Bump dependabot/fetch-metadata to 1.6.0
=> ci: Update lewagon/wait-on-check-action to fix update workflow

.github/workflows/test.yml
The workflows are run twice when we push to a PR branch. See https://github.com/webdriverio/selenium-standalone/pull/886/checks.
* Only run the workflow once when we push to a PR branch
The checks should not run for `(push)`, only `(pull_request)`.
=> ci: Do not run workflow twice for a PR

.github/workflows/test.yml, .gitignore, docs/API.md, lib/check-args.js, lib/check-started.js, lib/compute-download-urls.js, lib/default-config.js, lib/driver-starter.js, lib/install-utils.js, lib/install.js, lib/start.js, package-lock.json, package.json, test/check-args-test.js, test/compute-download-urls-test.js, test/default-downloads-test.js, test/only-driver-tests.js, test/process-killer-test.js, tsconfig.json
* Add TypeScript to check JavaScript
* Add `nyc` to check code coverage (to see what I can change with confidence)
* Add `"build"` script that can fail in the pipeline
* Add JSDoc comments to refine types
* Minor / low risk code changes
* I've pushed my WIP so there isn't a huge PR to review.
* There are still 16 problems reported by TypeScript.
* The type definitions could probably be extracted into a better spot. :thinking:
* Add tests before changing the untested code
* Research how to resolve this issue with `_handle` not being defined. I'm not sure what to replace that with. :shrug: 
```
test/only-driver-tests.js:97:21 - error TS2339: Property '_handle' does not exist on type 'ChildProcess'.
assert(process1._handle);
```
=> style: Begin migration to TypeScript

package-lock.json, package.json
- Failing tests should fail CI pipeline
- Downgrade `chai` from 5.1.0 to 4.4.1
- The intent of the `"test"` script was to run tests with v3 and v4 and always generate the combined coverage report.
I incorrectly used a command like `test:v3 && test:v4; report`. This does not fail when the tests fail. :facepalm:
- With the tests always passing, the Dependabot PR for `chai` v5 merged. :facepalm:
=> ci: Fix test step unexpectedly passing'

.github/dependabot.yml, lib/compute-download-urls.js, package-lock.json, package.json, test/no-reinstall.js
Remove axios dependecy due to this module has an error when the request is made via proxy (https://github.com/axios/axios/issues/4531#issuecomment-1608140085). 
Selenium-standalone has got http client that is better for this job.
`
2024-02-29T22:19:28.010Z - [selenium-standalone] [start] error installing version 4.17.0 selenium STACK: AxiosError: Request failed with status code 501
at settle (/home/testrunner/run_test_env/TG-CHROM0-CCHD/sources/itests-orchard/node_modules/selenium-standalone/node_modules/axios/dist/node/axios.cjs:1967:12)
at IncomingMessage.handleStreamEnd (/home/testrunner/run_test_env/TG-CHROM0-CCHD/sources/itests-orchard/node_modules/selenium-standalone/node_modules/axios/dist/node/axios.cjs:3066:11)
at IncomingMessage.emit (node:events:526:35)
at endReadableNT …
=> Fix error with axios and proxies

HISTORY.md, docs/issuer-cerificate.md, lib/driver-starter.js, lib/get-selenium-status-url.js, lib/install-utils.js, lib/install.js, lib/log-error.js, lib/platformDetection.js, lib/processKiller.js, lib/start.js, lib/validation.js, package-lock.json, package.json, test/cli-parameters.js, test/compute-download-urls-test.js, test/get-selenium-hub-test.js, test/no-reinstall.js, test/validation-test.js, tsconfig.json
This PR is a few incremental changes to resolve problems reported by `tsc`.
I removed the `proxy` option. Based on [the docs](https://github.com/sindresorhus/got/blob/main/documentation/tips.md#proxying) it doesn't actually configure `got`. :facepalm:
=> fix: Resolve problems reported by the TypeScript compiler

.github/workflows/test.yml, HISTORY.md, README.md, docs/API.md, lib/check-started.js, lib/compute-download-urls.js, lib/install-utils.js, lib/install.js, lib/proxyManager.js, package-lock.json, package.json, test/no-reinstall.js, test/only-driver-tests.js
1. Added proxy for http, https requests for cases when the tool behind corporate proxy and system env HTTP,HTTPS were specified
2. Dropped support node12 as http and https are node14 tools
=> added proxy complience

.github/dependabot.yml, lib/compute-download-urls.js, lib/start.js, package-lock.json, package.json
1. set find-process's version to exact 1.4.7 (cause version above supports only node v20)
2. forced port 9515 by default for chrome,edge drivers (issue https://www.autoitscript.com/forum/topic/212201-chromedriver-issues-august-2024/)
3. added 'exact match feature' https://github.com/webdriverio/selenium-standalone/issues/917
=> fixed (find-process version, forced default port 9515 for chrome and edge driver), added exact match feature  
