webdriverio/selenium-standalone

- lib/install.js
Hopefully this provides a little more info when diagnosing failures
See https://github.com/Polymer/web-component-tester/issues/113
> Preserve error messages when downloading

- lib/install.js
- test/no-reinstall.js
Follows suggested implementation where ETAG and MD5 are compared to determine whether remote and local files are identical. 
After installation, ZIP files are stored locally for future reference.
Fixes #50
> Ensure files are downloaded once.

- lib/start.js
The issue is gone with this fix.
> Added empty handlers to stdout and stderr to fix issue #83.

- lib/start.js
- package.json
- Do not callback twice when process already exists
- Error message more clear
- Bump some packages
> Fix for issue #104:

- lib/default-config.js
```sh
selenium-standalone install --version=2.46.0 --drivers.chrome.version=2.16
```
works fine, so bumping the default versions to latest.
> Update default versions

- README.md
see also merged PR https://github.com/vvo/selenium-standalone/pull/89
> add doc for role, hub and port option

- README.md
Let me know if I got it right, I'm no shell guru :sweat_smile:
> Add tip about killing the server in the background

- package.json
* name changed from URIjs to urijs
* increase version number from 1.15.0 to 1.16.1
> Update package name and version of urijs

- README.md
`pkill java` kills any Java process.
> Make the process killing more accurate in the docs

- lib/install.js
This chmod may not be necessary in some cases, and it breaks our ability to test in Docker. I'm sure I got some idioms wrong, and would be happy to fix them. Just let me know what to do.
> Check if we can read and execute before chmoding.

- HISTORY.md
- README.md
- lib/default-config.js
- test/get-selenium-hub-test.js
> Use HTTPS URLs when possible.

- lib/install.js
> Support for node.js 0.10.x

- lib/install.js
- lib/start.js
- test/programmatic.js
Reverts vvo/selenium-standalone#165
> Revert "Do not merge the install/start options with the default options."

- bin/selenium-standalone
- lib/install.js
- lib/start.js
- test/no-reinstall.js
- test/programmatic.js
Still allows to overwrite specific options on the CLI.
Second attempt :) Hope this addresses the points mentioned in
https://github.com/vvo/selenium-standalone/pull/165#issuecomment-188162273
See #165 and #128.
> Merge drivers with default options, but only those specified.

- lib/default-config.js
* Updates the default chromedriver install to latest 2.22
@vvo
> Chromedriver version bump

- lib/default-config.js
This version should fix the issue with Firefox 47 and onwards as per https://github.com/seleniumhq/selenium/issues/2110#issuecomment-229684461
> Update selenium to 2.53.1

- lib/install.js
selenium itself, ie, chrome, firefox
> expectedRequests should be 4 after firefox driver

- lib/install.js
> Add possibility to configure proxy via parameter 'proxy' like

- lib/start.js
First thank you for your work on this project! It's really helpful. I updated the error message because this sort of thing would have prompted me to check what version of java the server was trying to start on (machine has java8 but was trying to start on java6). I know there is a couple issues open about this error message so hopefully this can close 1-2 of them.
> Make error message more descriptive.

- lib/default-config.js
There's a new release of geckodriver out.
> Update geckodriver to 0.10.0

- lib/compute-download-urls.js
> fix firefox platform for mac OS

- lib/compute-download-urls.js
Fixes download url for beta versions:
3.0.0-beta2 --> 3.0-beta2
> Download URL beta version fix

- README.md
Update the examples so they contain the latest working versions of drivers and Selenium.
> Update driver and selenium versions in code examples

- lib/compute-download-urls.js
> Support geckodriver v0.9.0 and v0.8.0

- lib/default-config.js
Updated default value for Chrome driver version
> Lastest version of Chrome driver

- README.md
- bin/selenium-standalone
Add a `--config` option in CLI to specify options in a config file (See #230)
> Add a config file option (#230)

- README.md
- bin/selenium-standalone
Reverts vvo/selenium-standalone#236
> Revert "Add a config file option (#230)"

- LICENSE
Would you consider adding someone or some organization directly into the license file as the copyright holder?
This PR is just a suggestion, adding those listed in the authors file as copyright holders.
Thanks.
> adding copyright holders

- lib/compute-download-urls.js
- test/compute-download-urls-test.js
Several fixes in download urls (and a little bit of refactoring).
It should fix #250
> Fix download urls

- lib/default-config.js
* Sets default geckodriver installation to most current version
cc. @vvo
> geckodriver version bump

- lib/default-config.js
Changelogs:
- [Selenium](https://raw.githubusercontent.com/SeleniumHQ/selenium/master/java/CHANGELOG)
- [Internet Explorer](https://raw.githubusercontent.com/SeleniumHQ/selenium/master/cpp/iedriverserver/CHANGELOG)
- [Geckodriver](https://github.com/mozilla/geckodriver/releases/tag/v0.16.0)
> Update for lastest version of Selenium and Geckodriver

- bin/selenium-standalone
- lib/compute-download-urls.js
- lib/compute-fs-paths.js
- lib/default-config.js
- lib/install.js
- lib/microsoft-edge-releases.js
- lib/start.js
- package.json
- test/compute-download-urls-test.js
- test/default-downloads-test.js
Vincent, I'm using your library and wanted to test on Microsoft Edge. I added the possibility to install and use Microsoft Edge web driver following this: https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/#downloads
Hope you found it usefull and merge it to the master branch.
I didn't added tests because other tests were failing for me before even touch a line of code.
> Add Microsoft Edge Web Driver

- README.md
- lib/install.js
Not tested thoroughly (hard for me to reproduce, too), but it looks like I just need to configure `request`? Should fix #304
> fixes #304 - added timeout option to request

- lib/microsoft-edge-releases.js
allow edge webdriver 17134 to be recognised as valid version
> recognise MicrosoftWebDriver 17134

- .dockerignore
- Dockerfile
- README.md
- lib/install.js
How to test:
`docker build -f Dockerfile -t vvo/selenium-standalone . --rm && docker run -p 4444:4444  vvo/selenium-standalone`
Spins up a Docker with the latest FF and Chrome + selenium-standalone running on 4444
> Docker support

- scripts/release.sh
* Build latest version of Docker image, tag it and push it to Docker hub for both tags "new release version" and "latest"
* Added comment + minore refactoring
* Get application new version from `package.json` using generic `node` command rather than `json` command
> Add update of Docker image in release script

- lib/default-config.js
> Chromedriver 2.41

- lib/default-config.js
- test/default-downloads-test.js
fixes #434 
Updated driver versions to the latest available
> chore: Update binaries versions

- lib/compute-fs-paths.js
- lib/install.js
`chmod` is not executed for `chromiumedge`, the PR fixes that.
> Fix chromiumedge privileges

- lib/default-config.js
- lib/install.js
respect `libc++.dylib` shipped along with edge driver
fixes #488
> Fix chromiumedge download on MacOS

- .travis.yml
> remove some node versions

- Dockerfile
- docker/Dockerfile
Update NodeJS to 12 in Dockerfiles
> Update NodeJS to 12 in Dockerfiles

- lib/default-config.js
update iedriver version to `3.150.1`
> update iedriver version

- bin/selenium-standalone
- lib/check-started.js
- lib/default-config.js
- lib/install.js
- lib/start.js
- test/cli-parameters.js
- test/default-downloads-test.js
Avoid mutating default config as far as it causes some issues in programmatic usage
> Avoid mutating default config

- .vscode/launch.json
- lib/check-paths-existence.js
- lib/check-started.js
- lib/compute-download-urls.js
- lib/get-selenium-status-url.js
- lib/isSelenium4.js
- lib/start.js
- test/get-selenium-hub-test.js
> Selenium v4 

- lib/compute-download-urls.js
- lib/default-config.js
> (#589) Get fallback version if bundle is not available for wanted platform

- lib/install-utils.js
- lib/install.js
Removes callback for `isUptoDate` method!
> Remove callback in install-utils.js

- lib/install-utils.js
- lib/install.js
Removes callback in install-utils `checksum`
> Remove callback and replace with promise

- docs/API.md
This PR fixes dead link to default config
> fix dead link to default config

- docs/API.md
> docs: update basePath documentation

- lib/check-started.js
Also added possibility customize timeouts via env variables SELENUIM_CHECK_STARTED_TIMEOUT and SELENUIM_CHECK_STARTED_PAUSE
>  fixed timeout for server started checks #617

- lib/get-selenium-status-url.js
- package-lock.json
- test/compute-download-urls-test.js
- test/get-selenium-hub-test.js
fixes #616 
now with fixed unittests
> fixed args prefix for selenium3

- docs/API.md
- docs/CLI.md
- lib/default-config.js
- lib/start.js
- test/process-killer-test.js
like continuation https://github.com/webdriverio/selenium-standalone/pull/838 
@christian-bromann I think it worth to try your point of view. Believe everything should work.
> killing by default

- .github/dependabot.yml
- lib/check-paths-existence.js
- lib/compute-download-urls.js
- lib/compute-fs-paths.js
- lib/get-selenium-status-url.js
- package-lock.json
- package.json
Removed fs-extra package from dependencies since it was used in one place, 
nodejs has fs.existsSync, in this case it is not a long check.
Removed global context reference from functions body and some code style alignment
> chore/update code format, remove one place package usage

- lib/start.js
Hi @christian-bromann  this is fix for https://github.com/webdriverio/selenium-standalone/issues/736
> split by , if opts.javaArgs is string from cli

- HISTORY.md
- docs/API.md
- package-lock.json
- package.json
related to https://github.com/webdriverio/selenium-standalone/issues/669
> resolved onCancel bug and polish docs
